Hods 233 : Addee CtUtr ans SaUtr for Corporations and accompanying tests.
parkeradam/api-platform-test-user pull request #1
Opened 2021-06-11 13:00 UTC by parkeradam

2021-06-14 08:11 UTC, ajchilts requested changes

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> +      saUtr <- whenF(SELF_ASSESSMENT)(generateSaUtr)
Any reason we have changed the formatting here? I prefer it all lined up?

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> +      saUtr <- whenF(SELF_ASSESSMENT)(generateSaUtr)
As above

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> +      firstName = generateFirstName
As above

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> +    employerReferenceGenerator.sample.get.toString
As above. Why the change to the formatting?

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> +    val checkCharacter = calculateCheckCharacter(randomCode)
As above

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> +    val checkCharacter = calculateCheckCharacter(randomCode)
As above

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> -  def this(seed: Int) = this(new scala.util.Random(seed))
Why have we deleted this?

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> -  def this(seed: Int) = this(new scala.util.Random(seed))
Why have we deleted this?

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> -  def this(seed: Int) = this(new scala.util.Random(seed))
Why have we deleted this?

2021-06-14 08:11 UTC, ajchilts commented on app/uk/gov/hmrc/testuser/services/Generator.scala
> -  def this(seed: Int) = this(new scala.util.Random(seed))
Why have we deleted this?

2021-06-15 16:04 UTC, Luka-Abey approved these changes

2021-06-16 12:11 UTC, ajchilts approved these changes

2021-06-16 12:12 UTC, ajchilts commented
Fantastic work @parkeradam :-)

2021-06-18 12:02 UTC, ajchilts requested changes

2021-06-18 12:02 UTC, ajchilts commented on conf/app.routes
> +GET         /organisations/crn/:crn             uk.gov.hmrc.testuser.controllers.TestUserController.fetchOrganisationByCrn(crn: uk.gov.hmrc.testuser.models.Crn)
Why is this in `testuser.models` and not in `domain` like the others?

2021-06-21 15:22 UTC, parkeradam commented on conf/app.routes
> +GET         /organisations/crn/:crn             uk.gov.hmrc.testuser.controllers.TestUserController.fetchOrganisationByCrn(crn: uk.gov.hmrc.testuser.models.Crn)
Becase Crn is not defined in the Domain Library (or if it is I couldnt find it). As such I implemented a similar class locally.

2021-06-21 16:07 UTC, merged